version: "3.8"

services:
  postgres:
    image: postgres:15
    env_file:
      - ./config/.env.backend
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    image: tokamaknetwork/trh-backend
    command: >
      sh -c "
        apk add --no-cache wget bash &&
        wget https://raw.githubusercontent.com/tokamak-network/trh-sdk/main/setup.sh &&
        chmod +x setup.sh &&
        ./setup.sh &&
        echo 'Dependency installation completed.'
    "
    ports:
      - "8000:8000"
    env_file:
      - ./config/.env.backend
    depends_on:
      - postgres
    restart: unless-stopped

  frontend:
    image: tokamaknetwork/trh-frontend
    ports:
      - "3000:3000"
    env_file:
      - ./config/.env.frontend

volumes:
  postgres_data:
